# Generated by Django 3.0.4 on 2020-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('foods_id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=40, verbose_name='食材の名前')),
                ('texture', models.IntegerField(verbose_name='食感')),
                ('Allergy', models.IntegerField(verbose_name='アレルギー物質')),
                ('temperature', models.IntegerField(verbose_name='温度')),
                ('Halal', models.BooleanField(verbose_name='ハラル')),
                ('volume', models.IntegerField(verbose_name='腹持ちの良さ')),
                ('Prefecture', models.IntegerField(default=0, verbose_name='何県のあれか')),
                ('calorie', models.IntegerField(verbose_name='カロリー')),
                ('meat', models.BooleanField(verbose_name='肉入りかどうか')),
                ('fish', models.BooleanField(verbose_name='魚入りかどうか')),
                ('season', models.IntegerField(verbose_name='旬')),
                ('major_or_minor', models.BooleanField(verbose_name='有名かどうか')),
                ('difficulty', models.IntegerField(verbose_name='難度')),
                ('rice_or_bread', models.IntegerField(default=0, verbose_name='パンかご飯かそれいがいか')),
            ],
        ),
    ]
