# Generated by Django 3.0.4 on 2020-03-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='taste',
            field=models.IntegerField(default=0, verbose_name='味'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choices',
            name='texture',
            field=models.CharField(max_length=255, verbose_name='食感'),
        ),
    ]
