# Generated by Django 3.0.4 on 2020-03-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0003_choices_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='Allergy',
            field=models.CharField(max_length=50, verbose_name='アレルギー物質'),
        ),
    ]
