# Generated by Django 3.0.4 on 2020-03-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0004_auto_20200322_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=255, verbose_name='問題')),
                ('answer1_text', models.CharField(max_length=100, verbose_name='選択肢1')),
                ('answer1_column', models.IntegerField(verbose_name='この選択肢で聞きだすタグの番号')),
                ('answer2_text', models.CharField(max_length=100, verbose_name='選択肢2')),
                ('answer2_column', models.IntegerField(verbose_name='この選択肢で聞きだすタグの番号')),
                ('answer3_text', models.CharField(max_length=100, verbose_name='選択肢3')),
                ('answer3_column', models.IntegerField(verbose_name='この選択肢で聞きだすタグの番号')),
                ('answer4_text', models.CharField(max_length=100, verbose_name='選択肢4')),
                ('answer4_column', models.IntegerField(verbose_name='この選択肢で聞きだすタグの番号')),
                ('answer1_get_ans', models.CharField(max_length=50, verbose_name='ゲットした解答')),
            ],
        ),
    ]
