# Generated by Django 3.0.4 on 2020-03-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0005_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer2_get_ans',
            field=models.CharField(default=0, max_length=50, verbose_name='ゲットした解答'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer3_get_ans',
            field=models.CharField(default=1, max_length=50, verbose_name='ゲットした解答'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answer4_get_ans',
            field=models.CharField(default=1, max_length=50, verbose_name='ゲットした解答'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer1_column',
            field=models.CharField(max_length=100, verbose_name='この選択肢で聞きだすタグの番号'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer2_column',
            field=models.CharField(max_length=100, verbose_name='この選択肢で聞きだすタグの番号'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer3_column',
            field=models.CharField(max_length=100, verbose_name='この選択肢で聞きだすタグの番号'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer4_column',
            field=models.CharField(max_length=100, verbose_name='この選択肢で聞きだすタグの番号'),
        ),
    ]
