# Generated by Django 3.0.4 on 2020-03-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kensaku', '0006_auto_20200324_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer1_column',
            field=models.CharField(max_length=100, verbose_name='この選択肢で聞きだすタグの名前'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer2_column',
            field=models.CharField(max_length=100, verbose_name='この選択肢で聞きだすタグの名前'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer3_column',
            field=models.CharField(max_length=100, verbose_name='この選択肢で聞きだすタグの名前'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer4_column',
            field=models.CharField(max_length=100, verbose_name='この選択肢で聞きだすタグの名前'),
        ),
    ]
